version: '3.8'
services:
  poky:
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        YOCTO_DISTRO: kirkstone
    image: naokitakahashi12/docker-yocto:kirkstone
    tty: true
    volumes:
      - ./build:/home/builder/build:rw
      - ./conf:/home/builder/build/conf:rw
      - ./layers:/home/builder/layers
    command: >
      /bin/bash
